# Generated by Django 3.2.9 on 2021-11-19 11:16

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eshop_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_tags', '0001_initial'),
        ('eshop_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('full_info_description', models.TextField(blank=True, default=0, null=True, verbose_name='توضیحات کلی')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_products.models.upload_image_path, verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('Weight', models.CharField(default='', max_length=200)),
                ('Materials', models.CharField(default='', max_length=200)),
                ('Dimensions', models.CharField(default='', max_length=200)),
                ('Other_Info', models.CharField(default='', max_length=200)),
                ('is_especial', models.BooleanField(blank=True, default=False, null=True)),
                ('offer', models.BooleanField(blank=True, default=False, null=True)),
                ('our_suggestion', models.BooleanField(blank=True, default=False, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='eshop_categories.ProductsCategory', verbose_name='دسته بندی ها')),
                ('tag', models.ManyToManyField(blank=True, related_name='products', to='eshop_tags.Tag', verbose_name='تگ ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=eshop_products.models.upload_gallery_image_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.productslist', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eshop_products.productslist')),
            ],
        ),
    ]
