# Generated by Django 3.2.9 on 2021-11-19 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_remove_productslist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
