# Generated by Django 3.2.9 on 2021-11-19 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_productslist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='status',
            field=models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], default=django.utils.timezone.now, max_length=1, verbose_name='وضعیت'),
            preserve_default=False,
        ),
    ]
