# Generated by Django 3.2.9 on 2021-11-19 17:58

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tags', '0001_initial'),
        ('eshop_categories', '0001_initial'),
        ('eshop_products', '0004_productslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='eshop_categories.ProductsCategory'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='full_info_description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='status',
            field=models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='products', to='eshop_tags.Tag'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
