# Generated by Django 3.2.9 on 2021-11-20 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_productsgallery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsgallery',
            name='status',
            field=models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
