# Generated by Django 3.2.9 on 2021-11-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0008_productsgallery_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
