# Generated by Django 3.2.9 on 2021-11-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0010_auto_20211129_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslist',
            name='hits',
        ),
    ]
