# Generated by Django 3.2.9 on 2021-11-29 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0011_remove_productslist_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='crated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crated', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.ipaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.productslist')),
            ],
        ),
        migrations.AddField(
            model_name='productslist',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='eshop_products.ProductHit', to='eshop_products.IPAddress'),
        ),
    ]
