# Generated by Django 3.2.9 on 2021-11-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_color',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
