# Generated by Django 3.2.9 on 2021-11-19 11:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان در URL')),
                ('is_sub', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eshop_categories.productscategory')),
            ],
        ),
    ]
