# Generated by Django 3.2.9 on 2021-11-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=models.CharField(max_length=100),
        ),
    ]
