# Generated by Django 3.2.9 on 2021-11-30 12:19

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0004_banner_1_banner_2_banner_3_homeslider_homeslider2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=eshop_settings.models.upload_image_path)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
